version: "3"

networks:
  linguafinder:

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "app:${TAG}"
    depends_on:
      - database
      - redis
    networks:
      - linguafinder
    ports:
      - "13000:3000"
    command: bundle exec puma -C config/puma.rb
    env_file:
      - ./.env
    volumes:
      - app-sync:/mnt/app

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "app:${TAG}"
    depends_on:
      - database
      - redis
    networks:
      - linguafinder
    env_file:
      - ./.env
    volumes:
      - app-sync:/mnt/app
    command: bundle exec sidekiq -C config/sidekiq.yml

  database:
    image: postgres:9.6.15
    networks:
      - linguafinder
    expose:
      - 5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    networks:
      - linguafinder
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  redis-data:
  app-sync:
    external: true
