default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV["DB_POOL"] || 5 %>
  variables:
    statement_timeout: <%= ENV["DB_TIMEOUT"] || 5000 %>

development:
  <<: *default
  database: lingua_finder_dev
  host: postgres

test:
  <<: *default
  database: lingua_finder_test
  host: postgres

production:
  <<: *default
  database: lingua_finder_prod
  url: <%= ENV['DATABASE_URL'] %>
